services:
  mongo:
    image: mongo
    restart: always
    container_name: mongo
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    environment: 
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongo-data:/data/db

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    ports:
      - "${MONGO_EXPRESS_PORT}:${MONGO_EXPRESS_PORT}"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo:${MONGO_PORT}/
      ME_CONFIG_BASICAUTH: false

  nodeapp:
    build: .
    container_name: nodeapp
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - mongo
      - mongo-express
    environment:
      MONGO_URI: ${MONGO_URI}
      APP_PORT: ${APP_PORT}

volumes:
  mongo-data: